name: CCSeasonOne
author: EmeraldMC
api: 3.0.0-ALPHA12
version: 1.0.0
main: EmeraldMC\Commands\Main
commands:
 godkit:
  description: cowcraft godkits
 spawners:
  description: cowcraft spawners
 spawnerupgrade:
  description: cowcraft spawner upgrades
 traps:
  description: cowcraft traps
 ceshop:
  description: cowcraft customenchants shop
 ccseason:
  description: cowcraft current season
 ccversion:
  description: cowcraft software version
  
